version: "2.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: rustservice_dev:0.1
    volumes:
      - .:/code
    entrypoint: systemfd --no-pid -s 0.0.0.0:5000 -- cargo watch -x run
    working_dir: /code
    ports:
      - "5000:5000"